name: Events Demo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SUN'

permissions:
  contents: read

jobs:
  create-shell-script:
    name: Create a shell script
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: tests
      - run: |
          touch script.sh
          cat >> script.sh << 'EOF'
          #!/bin/bash
          echo "this is a scheduled event executed at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          EOF
          chmod +x script.sh
          ./script.sh
  run-reusable-action:
    name: Import and execute a re-usable action file
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mood: ['happy', 'sad', 'neutral']

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/reusable-actions
        with: 
          environment: staging
          mood: ${{ matrix.mood }}
