name: Events Demo

on:
  issues:
    types: [opened, edited, milestoned]

permissions:
  contents: read

jobs:
  create-shell-script:
    name: Create a shell script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: tests
      - run: |
          touch script.sh
          cat >> script.sh << 'EOF'
          #!/bin/bash
          echo "this is from script.sh"
          EOF
          chmod +x script.sh
          ./script.sh

